services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - appnet
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  webserver:
    build: ./app
    container_name: webserver
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
